"use client";
import type { Metadata } from "next";
import { Inter, Fredoka, Lato, Averia_Serif_Libre } from "next/font/google";
import Header from "./components/Header";
import "./globals.css";
import { SliderMenuProvider } from "./Utilities/SliderMenuContext";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/swiper-bundle.css";
import Footer from "./components/FooterComponentsFolder/Footer";

const inter = Inter({ subsets: ["latin"] });
const fredoka = Fredoka({ subsets: ["latin"] });
const lato = Lato({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lato",
});
const averiaSerifLibre = Averia_Serif_Libre({
  subsets: ["latin"],
  weight: "300",
  variable: "--font-averiaSerifLibre",
  style: "italic",
});

const metadata: Metadata = {
  title: "LOGO-Testsite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${averiaSerifLibre.variable} ${lato.variable}`}>
        <SliderMenuProvider>
          <Header />
          {children}
          <Footer />
        </SliderMenuProvider>
      </body>
    </html>
  );
}
